config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :activities
  root 'information_pages#home'

end

app/models/activity.rb
class Activity < ActiveRecord::Base
  belongs_to :user

  validates :name, presence: true
  validates :user, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :activities
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController
  before_action :authenticate_user!

  def index
    @activities = current_user.activities
  end

  def new
    @activity = Activity.new
  end

  def show
    @activity = Activity.find(params[:id])
  end

  def create
    @activity = current_user.activities.new(activity_attributes)

    if @activity.save
      flash[:success] = "Activity successfully created."
      redirect_to @activity
    else
      render :new  
    end
  end

  def edit
    @activity = Activity.find(params[:id])
  end

  def update
    @activity = current_user.activities.find(params[:id])

    if @activity.update_attributes(activity_attributes)
      flash[:success] = "Activity successfully updated."
      redirect_to @activity
    else
      render :edit
    end
  end

  def destroy
    @activity = current_user.activities.find(params[:id]) 
    @activity.destroy
    flash[:notice] = "Activity successfully deleted."
    redirect_to activities_path
  end


  private

  def activity_attributes
    params.require(:activity).permit(:name)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/information_pages_controller.rb
class InformationPagesController < ApplicationController  
  def home
  end
end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/information_pages_helper.rb
module InformationPagesHelper
end

app/views/activities/edit.html.haml
%fieldset
  %legend Edit activity

= form_for @activity do |f|
  = render 'shared/form_error_messages', object: f.object
  .form-group
    = f.label      :name
    = f.text_field :name
  .form-group
    = f.submit "Submit"

= link_to "Delete", activity_path(@activity), method: :delete, 
                                              data: {confirm: "You sure?"}, 
                                              title: @activity.name

app/views/activities/index.html.haml
= link_to "New activity", new_activity_path

= render "shared/activities"

app/views/activities/new.html.haml
%fieldset
  %legend New activity

= form_for @activity do |f|
  = render 'shared/form_error_messages', object: f.object
  .form-group
    = f.label      :name
    = f.text_field :name
  .form-group
    = f.submit "Submit"

app/views/activities/show.html.haml
.activity-show
  %dl.dl-horizontal
    %dt Name:
    %dd= @activity.name
    %dt Create time
    %dd= @activity.created_at
  = link_to "Edit", edit_activity_path(@activity)

app/views/layouts/application.html.haml
!!! 5
!!!
%html
  %head
    %meta{name: "viewport", content: "width=device-width, initial-scale=1"}
    %title My Timestamps
    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbo-links-track' => true
    = csrf_meta_tags

  %body
    .navbar.navbar-inverse.navbar-fixed-top{role: "navigation"} 
      .container
        .navbar-header
          %button.navbar-toggle{type: "button", 
                                "data-toggle" => "collapse",
                                "data-target" => ".navbar-collapse"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to "My Timestamps", root_path, class: "navbar-brand"
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li.active
              %a{href: "#"} Home
            %li
              %a{href: "#"} Away
          .navbar-right
            %ul.nav.navbar-nav
            - if user_signed_in?
              %li
                = link_to "Sign out", destroy_user_session_path, method: :delete
            - else
              %li
                = link_to "Sign in", new_user_session_path

  .container    
    .content
      - if flash[:notice]
        %p.alert.alert-info
          = flash[:notice]

      - if flash[:success]
        %p.alert.alert-success
          = flash[:success]

      - if flash[:alert]
        %p.alert.alert-danger
          = flash[:alert]

      %h1 My Timestamps

      %div
        - if !user_signed_in?
          = link_to "Sign up", new_user_registration_path

      = yield
      %p
        = debug(params) if Rails.env.development? 

app/views/shared/_activities.html.haml
%h3 Activities

- if @activities.any?
  = "#{@activities.count} #{'activity'.pluralize(@activities.count)}"
  %table.activities-list
    - @activities.each do |activity|
      %tr{id: "activity#{activity.id}"}
        %td= link_to activity.name, activity_path(activity.id)
        %td= activity.created_at
- else
  No activities

app/views/shared/_form_error_messages.html.haml
- if object.errors.any?
  .error_explanation
    .alert.alert-error
      = "The form contains #{object.errors.count} #{'error'.pluralize(object.errors.count)}"
      %ul
        - object.errors.full_messages.each do |message|
          %li #{message}